<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE keyboard-layout
[
   <!ELEMENT layout (layout-name, version,(key)*)>
      <!ELEMENT layout-name (#PCDATA)>
      <!ELEMENT version (#PCDATA)>
      
      <!ELEMENT key (scancode, qwertz-name,(layer)*)>     <!-- repräsentiert eine Taste -->
      <!ATTLIST key id CDATA #REQUIRED >        <!-- der Index der Taste (wie auf http://www.cherry.de/deutsch/service/service_faq_id141_multiboard.htm) -->
         <!ELEMENT scancode (#PCDATA)>          <!-- der Scancode der Taste (Code Set 2, hexadezimal) -->
         <!ELEMENT qwertz-name (#PCDATA)>       <!-- autohotkey-Bezeichnungen der Taste beim qwertz-layout -->
         <!ELEMENT layer ((character | actionkey | deadkey)?,(deadkey-combo)*)> <!-- eine Ebene einer Taste, kann beliebig viele DeadKey-Kombinationen, aber nur eine Standardaktion enthalten -->
         <!ATTLIST layer id CDATA #REQUIRED>
            <!ELEMENT character (sign, unicode, description?)> <!-- steht für ein Zeichen -->
               <!ELEMENT sign (#PCDATA)>        <!-- das Zeichen selbst -->
               <!ELEMENT unicode (#PCDATA)>     <!-- die offizielle Unicode-Codierung („U+x“)-->
               <!ELEMENT description (#PCDATA)> <!-- Beschreibung, optional (bis jetzt nur die unicode-bezeichnung, ist das optimal, oder evtl noch ein feld?) -->
            <!ELEMENT deadkey (deadkey-name, character)> <!-- steht für einen Deadkey -->
               <!ELEMENT deadkey-name (#PCDATA)>
            <!ELEMENT actionkey (#PCDATA)>      <!-- eine Aktionstaste wie links, rechts, enter… siehe Namensliste (die noch erstellt werden muss). -->
            <!ELEMENT deadkey-combo (deadkey-name, character)>
]>

<?xml-stylesheet type="text/xsl" href="neo20_xml-darstellung.xsl" ?>

<layout>

   <layout-name>NEO - ergonomisches Tastaturlayout</layout-name>
   <version>2.0 build 1</version>

   <key id="1">
      <scancode>0E</scancode>
      <qwertz-name>^</qwertz-name>
      <layer id="1">
         <deadkey>
            <deadkey-name>circumflex</deadkey-name>
            <character>
               <sign>ˆ</sign>
               <unicode>U+02C6</unicode>
               <description>MODIFIER LETTER CIRCUMFLEX ACCENT</description>
            </character>
         </deadkey>
      </layer>
      <layer id="2">
         <deadkey>
            <deadkey-name>caron</deadkey-name>
            <character>
               <sign>ˇ</sign>
               <unicode>U+02C7</unicode>
               <description>CARON</description>
            </character>
         </deadkey>
      </layer>
      <layer id="3">
         <deadkey>
            <deadkey-name>brevis</deadkey-name>
            <character>
               <sign>˘</sign>
               <unicode>U+02D8</unicode>
               <description>BREVE</description>
            </character>
         </deadkey>
      </layer>
      <layer id="4">
         <deadkey>
            <deadkey-name>querstrich</deadkey-name>
            <character>
               <sign>-</sign>
               <unicode>U+002D</unicode>
               <description>HYPHEN-MINUS</description>
            </character>
         </deadkey>
      </layer>
      <layer id="5">
         <deadkey>
            <deadkey-name>mittenpunkt</deadkey-name>
            <character>
               <sign>·</sign>
               <unicode>U+00B7</unicode>
               <description>MIDDLE DOT</description>
            </character>
         </deadkey>
      </layer>
      <layer id="6">
         <deadkey>
            <deadkey-name>punkt darunter</deadkey-name>
            <character>
               <sign>.</sign>
               <unicode>U+002E</unicode>
               <description>FULL STOP</description>
            </character>
         </deadkey>
      </layer>
   </key>
   
   <key id="2">
      <scancode>16</scancode>
      <qwertz-name>1</qwertz-name>
      <layer id="1">
         <character>
            <sign>1</sign>
         </character>
         <deadkey-combo>
            <deadkey-name>circumflex</deadkey-name>
            <character>
               <sign>¹</sign>
               <unicode>U+00B9</unicode>
               <description>SUPERSCRIPT ONE</description>
            </character>
         </deadkey-combo>
      </layer>
      <layer id="2">
         <character>
            <sign>¶</sign>
            <unicode>U+00B6</unicode>
            <description>PILCROW SIGN</description>
         </character>
      </layer>
      <layer id="4">
         <character>
            <sign>½</sign>
            <unicode>U+00BD</unicode>
            <description>VULGAR FRACTION ONE HALF</description>
         </character>
      </layer>
   </key>
   
</layout>